### ISSUE TITLE
Text-Änderungen

### ISSUE THREAD

**Issue by cadeyrn** [MozillaDE/tiles-landing-page#10]
Text von Astrid:

Unabhängig von meinem Beruf, im sozialen Bereich, interessiere ich mich seit ca. 2004 kontinuierlich für die Entwicklung von Open Source Programmen und insbesondere für Firefox. Durch ständiges Aneignen von Kenntnissen konnte ich diese bald erfolgreich an andere Menschen weitervermitteln. Seit 2010 beteilige ich mich aktiv in der Gemeinschaft.

Mein Fokus liegt darauf, ganz konkret Menschen in akuten Situationen bei Firefox-Problemen zu helfen. Dabei ist es mir wichtig, ganz individuell auf den Menschen einzugehen und im Einzelfall, auch über das Projekt hinaus, weitreichendere Hilfestellungen und Aufklärung zu geben. Dabei unterstütze ich den Hilfesuchenden auch darin, die Fähigenkeiten in den Grundlagen von Computern und Internet weiterzuentwickeln. Die Firefox-Gemeinschaft im Rücken zu haben, mich mit ihnen auszutauschen und zusammenzuarbeiten ist für mich von enormer Bedeutung und eine Bereicherung.

(da waren ein paar Sachen auseinandergeschrieben, die zusammengehörten, Komma-Korrekturen, "seit" statt "ab")

Text von Sören:

"Firefox OS Gerätedokumentation" statt "Firefox OS Gerätdokumentation"

Etwas weiter unten:

"Wählen Sie aus, was Sie interessiert, und sagen Sie uns, wie Sie gerne helfen würden"

Bei "Ich helfe derzeit bei" steht bei Astrid Deutsches Firefox Forum und bei mir Firefox-Support-Forum. Bitte einheitlich machen (und vielleicht ohne das erste "-"). Das sollte natürlich auch konsistent mit de Chat bei Astrid sein.

Option a) Firefox Support-Forum / Firefox Support-Chat
Option b) Deutscher Firefox Hilfechat / Deutsches Firefox Forum

Also wenn es bei Astrid so bleibt, wie es schon ist, (Option b), dann auch bei mir "Deutsches Firefox Forum) oder wenn es bei mir so bleibt, wie es ist (Option a), dann bei Astrid "Firefox Support-Forum" und "Firefox Support-Chat".

**Comment by cadeyrn** [comment]
Noch eine Textänderung: unter meinem Kopf steht "Blog", wobei ich den Blog mehr als Mittel zum Zweck sehe. Sowas wie "Kommunikation" würde mir besser gefallen, da es mein Ziel ist, den Nutzern zu kommunizieren, was sich in der Welt von Mozilla tut.

**Comment by cadeyrn** [comment]
Ich hab nochmal über "Kommunikation" nachgedacht. Vielleicht klingt das doch ein wenig irreführend. Was hältst du von "Information"?

**Comment by MichaelKohler** [comment]
wie du magst, ich gebe dir bis morgen Abend Zeit, dir das zu überlegen :P
