### ISSUE TITLE
Lernen Sie uns kennen: Relevante Seiten verlinken

### ISSUE THREAD

**Issue by cadeyrn** [MozillaDE/tiles-landing-page#13]
Wenn ein Nutzer auf der Seite landet und sieht: "der Typ mit dem Namen Sören macht also eine Gerätedokumentation, das interessiert mich", sollte er wissen, wie er dahin kommt, also sollte das mit der Seite verlinkt werden. Oder wer den Text von Astrid liest und denkt "Ich brauch Support!" - Chat und Forum verlinken. usw.

Was auf jeden Fall verlinkt werden kann: Firefox Forum, Firefox Chat, der Blog, die Gerätedokumentation. Bei Mozilla Schweiz weiß ich nicht, ob es da etwas gibt, wo hin verlinkt werden kann - hat die Schweizer Community eine Webseite? Soll der Twitter-Account verlinkt werden? Das entscheidest am besten du @MichaelKohler. Events weiß ich auch nicht, eventuell die Reps Eventseite? Perfekt wäre es natürlich, wenn es einen Filter für die Reps Eventseite geben würde für Deutschland, Österreich und Schweiz gleichzeitig, aber ich fürchte, das gibt es nicht. Also wäre vermutlich ohne Einschränkung das beste, sollte man die Reps Eventseite verlinken wollen.

**Comment by MichaelKohler** [comment]
Hallo Sören, ich habe die Verlinkungen gemacht. Danke für deinen Input!

Zwei Sachen habe ich vorerst weggelassen: dein Blog und firefoxosdevices.org, ich muss zuerst abklären, ob wir überhaupt auf Seiten mit Werbung verlinken dürfen. Die Landing-Page ist direkt aus Firefox erreichbar und daher könnte Mozilla da was dagegen haben. Ich kläre das ab.

**Comment by cadeyrn** [comment]
Alles klar. Wobei mich wundern würde, wenn es ein Problem wäre, da ja die genannten Seiten nicht direkt in Firefox verlinkt sind, sondern nur auf der Webseite, auf der ja auch der Twitter- und der Facebook-Account verlinkt sind - beides ebenso mit Werbung. Meiner Meinung nach müsste man diese Links dann auch entfernen, wenn das wirklich ein Problem wäre. ;)

**Comment by MichaelKohler** [comment]
ist von Brian und Patrick abgesegnet

**Comment by cadeyrn** [comment]
Perfekt! Ich schlage im Falle von firefoxosdevices.org noch vor, dass du die deutsche Version verlinkst. :D

**Comment by MichaelKohler** [comment]
erledigt
