### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by cadeyrn** [MozillaDE/tiles-landing-page#14]
Wie schon auf der Mailingliste besprochen: das Responsive Design braucht Anpassungen. Bis runter 320px Bildschirmbreite sollten wir unterstützen.

**Comment by MichaelKohler** [comment]
@cadeyrn könntest du das bitte auf http://www.michaelkohler.info/mozilla/tiles-landing-page/ verifizieren?

**Comment by cadeyrn** [comment]
Bei einer Bildschirmbreite zwischen 320 und 500px gibt es noch immer einen horizontalen Scrollbalken. Das liegt am padding-right: 40px in der Klasse member-content, was am besten bei 1020px und weniger auf 0 gesetzt wird, da das die Breite ist, bei der sich die Liste "Ich helfe derzeit bei" unter dem Text befindet und nicht mehr links, sprich nicht mehr notwendig ist (auch wenn es bei dieser Breite noch keinen negativen Effekt hat).
