### ISSUE TITLE
"Ich helfe derzeit bei": Links schwer erkennbar

### ISSUE THREAD

**Issue by cadeyrn** [MozillaDE/tiles-landing-page#18]
Nachdem du alle meine Aufgaben erledigt hast und eine neue Version online ist (\o/), sehe ich jetzt noch ein ganz kleines Designproblem. Und zwar bei "Ich helfe derzeit bei" sind die Links jetzt ganz genauso dargestellt wie der Text. Es gibt zwar einen Hover-Effekt, aber man muss erst wissen, was davon der Link ist. Ich würde daher entweder, wenn es einen Link gibt, zumindest die ganze Zeile verlinken und nicht nur einen Teil oder aber den verlinkten Teil anders darstellen. Andere Farbe, unterstrichen und bei Hover die Unterstreichung wegnehmen, unterstreichen und bei Hover die Farbe ändern, irgendwas eben, damit man erkennt, was davon ein Link ist und was nicht. Im Footer sieht man auch gut, was Text und was Link ist.

Und wo ich das schreibe, fällt mir auch, dass die vier Links im Header keinen Hover-Effekt haben, da vielleicht auch eine Unterstreichung bei Hover wie im Footer hinzufügen.

**Comment by MichaelKohler** [comment]
@cadeyrn  Dann musst du das jeweils besser spezifizieren :P Vorschlag für eine Farbe, die passt?

**Comment by cadeyrn** [comment]
Wenn es eine Farbänderung sein soll, vielleicht ein ganz dezenter Unterschied wie rgb(210, 210, 210). Oder man macht an dieser Stelle die Links unterstrichen und bei Hover nicht. Im Prinzip spielt das keine große Rolle, hauptsache Text und Links können auseinandergehalten werden. :)
