### ISSUE TITLE
Fehler im Text

### ISSUE THREAD

**Issue by cadeyrn** [MozillaDE/tiles-landing-page#19]
Einen Textfehler habe ich noch gefunden:

Wir würden uns freuen, wenn wir auch Sie sich in Zukunft in der deutschsprachigen Gemeinschaft engagieren würden.

In dem Teil "wir auch Sie sich" stimmt irgendetwas nicht, wahrscheinlich ist das "wir" zu viel. ;)

**Comment by MichaelKohler** [comment]
weiterer Input von Hagen:
- "Fähigenkeiten"
- "mach mit" bei Jan
