### ISSUE TITLE
Designfehler in Safari

### ISSUE THREAD

**Issue by cadeyrn** [MozillaDE/tiles-landing-page#21]
Die vier Köpfe sind in Safari alle untereinander, nicht nebeneinander. Das muss unbedingt behoben werden, Safari ist für OS X das, was der Internet Explorer für Windows ist.

**Comment by MichaelKohler** [comment]
Das ist wegen flexbox. 99.9% der Leute werden sowieso über Firefox da drauf kommen.

**Comment by cadeyrn** [comment]
Wird von mozilla.de kein Link zu dieser Seite führen? Auf OS X verwenden die meisten Leute nämlich mit Sicherheit nicht Firefox.

**Comment by cadeyrn** [comment]
Und Safari unterstützt Flexbox mit Vendor-Präfix. Für Android und iOS wäre das ebenso notwendig, also nicht nur OS X. ;)

**Comment by MichaelKohler** [comment]
Wenn wir das irgendwann Mal als Unterseite mozilla.de verlinken (im Menü oder so), müssten wir auch das Design von mozilla.de anpassen, oder nicht? ;)

**Comment by cadeyrn** [comment]
mozilla.de hat nicht einen einzigen Darstellungsfehler in Safari. ;)

**Comment by MichaelKohler** [comment]
Nein, aber ein komplett anderes Layout ;)

**Comment by MichaelKohler** [comment]
Also im Vergeich zur Tiles-Landing-Page meine ich, nicht zwischen den Browsern verglichen

**Comment by cadeyrn** [comment]
Achso, okay. :) Steht das auf der Roadmap? :P

Es stimmt schon, ein einheitliches Design wäre schön. Vor allem dreht sich diese Seite ums Mitmachen und dann haben wir noch http://mozilla.de/mitmachen/. Meiner Meinung nach wäre diese Seite dann obsolet und sollte durch die neue Seite ersetzt werden, aber du hast natürlich Recht, dass dann vorher mozilla.de angepasst werden müsste, denn das wäre sonst wirklich komisch. Die in der Hauptnavigation verlinkten Seiten sollten schon einheitlich aussehen. Also wohl ein Thema für später…

**Comment by MichaelKohler** [comment]
komplett einverstanden. Das momentane Ziel wäre es vorerst den Inhalt von mozilla.de zu überarbeiten, aber Redesign wird auch irgendwann nötig sein, denke ich.
