### ISSUE TITLE
Nicht dringende Design-Fehler in Safari

### ISSUE THREAD

**Issue by cadeyrn** [MozillaDE/tiles-landing-page#22]
Issue #21 ist denke ich ein Launch-Blocker. Ich eröffne noch ein zweites Ticket für weitere Designprobleme, welche den Launch in meinen Augen nicht blocken müssen (aber behoben werden sollten):
- Text auf cta_background.jpg ist in Firefox vertikal zentriert, in Safari oben.
- "Ich helfe derzeit bei" ist in Firefox rechts vom Text, in Safari unter dem Text.

**Comment by MichaelKohler** [comment]
99.9% der Leute werden von Firefox da drauf kommen. Ausser wir wollen das sonst noch irgendwo verlinken, aber ja..
