### ISSUE TITLE
Linkänderung

### ISSUE THREAD

**Issue by cadeyrn** [MozillaDE/tiles-landing-page#24]
Dieser Link: https://www.soeren-hentzschel.at/category/mozilla/ ist nicht länger gültig und muss geändert werden, bitte auf die Startseite. Ich habe zwar eine Weiterleitung von https://www.soeren-hentzschel.at/category/mozilla/ auf https://www.soeren-hentzschel.at/mozilla/ eingerichtet, diese Kategorie beinhaltet aber nicht länger News über Firefox, Thunderbird etc., sondern Artikel, die keiner anderen Kategorie zugeordnet sind oder einer anderen Kategorie primär zugeordnet ist. In jedem Fall repräsentiert diese Kategorie nicht länger den Mozilla-Part des Blogs, wobei ja sowieso der gesamte Blog zu schätzungsweise 99,8 Prozent Mozilla-Themen beinhaltet, Startseite passt also.

**Comment by alex-pl** [comment]
Code ist ausgebessert. Muss jetzt nur noch am Server aktualisiert werden.

**Comment by MichaelKohler** [comment]
auf Produktion deployed
